//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Singleton_EntityBehaviorMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Singleton<EntityBehaviorMgr>), typeof(System.Object), "Singleton_EntityBehaviorMgr");
		L.RegFunction("Instance", Instance);
		L.RegFunction("New", _CreateSingleton_EntityBehaviorMgr);
		L.RegFunction("__tostring", Lua_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSingleton_EntityBehaviorMgr(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Singleton<EntityBehaviorMgr> obj = new Singleton<EntityBehaviorMgr>();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Singleton<EntityBehaviorMgr>.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Instance(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			EntityBehaviorMgr o = Singleton<EntityBehaviorMgr>.Instance();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}
}

