//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: AIMessage.proto
namespace AIMessage    
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_AI_RUN")]
  public partial class CS_AI_RUN : global::ProtoBuf.IExtensible
  {
    public CS_AI_RUN() {}
    
    private float _DestX;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"DestX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DestX
    {
      get { return _DestX; }
      set { _DestX = value; }
    }
    private float _DestY;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"DestY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DestY
    {
      get { return _DestY; }
      set { _DestY = value; }
    }
    private float _DestZ;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"DestZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DestZ
    {
      get { return _DestZ; }
      set { _DestZ = value; }
    }
    private ulong _ParasiteUID = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ParasiteUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ParasiteUID
    {
      get { return _ParasiteUID; }
      set { _ParasiteUID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_AI_RUN")]
  public partial class SC_AI_RUN : global::ProtoBuf.IExtensible
  {
    public SC_AI_RUN() {}
    
    private ulong _EntityUID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"EntityUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong EntityUID
    {
      get { return _EntityUID; }
      set { _EntityUID = value; }
    }
    private float _DestX;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"DestX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DestX
    {
      get { return _DestX; }
      set { _DestX = value; }
    }
    private float _DestY;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"DestY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DestY
    {
      get { return _DestY; }
      set { _DestY = value; }
    }
    private float _DestZ;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"DestZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DestZ
    {
      get { return _DestZ; }
      set { _DestZ = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_AI_ATTACK")]
  public partial class CS_AI_ATTACK : global::ProtoBuf.IExtensible
  {
    public CS_AI_ATTACK() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _Level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private float _Orientation;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Orientation", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Orientation
    {
      get { return _Orientation; }
      set { _Orientation = value; }
    }
    private ulong _ParasiteUID = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ParasiteUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ParasiteUID
    {
      get { return _ParasiteUID; }
      set { _ParasiteUID = value; }
    }
    private ulong _TargetUID = default(ulong);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"TargetUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong TargetUID
    {
      get { return _TargetUID; }
      set { _TargetUID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_AI_ATTACK")]
  public partial class SC_AI_ATTACK : global::ProtoBuf.IExtensible
  {
    public SC_AI_ATTACK() {}
    
    private int _Id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private int _Level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private ulong _EntityUID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"EntityUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong EntityUID
    {
      get { return _EntityUID; }
      set { _EntityUID = value; }
    }
    private float _Orientation;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Orientation", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Orientation
    {
      get { return _Orientation; }
      set { _Orientation = value; }
    }
    private ulong _Target;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Target", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong Target
    {
      get { return _Target; }
      set { _Target = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_AI_TURNFACE")]
  public partial class CS_AI_TURNFACE : global::ProtoBuf.IExtensible
  {
    public CS_AI_TURNFACE() {}
    
    private float _Orientation;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Orientation", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Orientation
    {
      get { return _Orientation; }
      set { _Orientation = value; }
    }
    private ulong _ParasiteUID = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ParasiteUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ParasiteUID
    {
      get { return _ParasiteUID; }
      set { _ParasiteUID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_AI_TURNFACE")]
  public partial class SC_AI_TURNFACE : global::ProtoBuf.IExtensible
  {
    public SC_AI_TURNFACE() {}
    
    private ulong _EntityUID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"EntityUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong EntityUID
    {
      get { return _EntityUID; }
      set { _EntityUID = value; }
    }
    private float _Orientation;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Orientation", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Orientation
    {
      get { return _Orientation; }
      set { _Orientation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_AI_SWITCHWEAPON")]
  public partial class CS_AI_SWITCHWEAPON : global::ProtoBuf.IExtensible
  {
    public CS_AI_SWITCHWEAPON() {}
    
    private int _Index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Index
    {
      get { return _Index; }
      set { _Index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_AI_SWITCHWEAPON")]
  public partial class SC_AI_SWITCHWEAPON : global::ProtoBuf.IExtensible
  {
    public SC_AI_SWITCHWEAPON() {}
    
    private ulong _EntityUID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"EntityUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong EntityUID
    {
      get { return _EntityUID; }
      set { _EntityUID = value; }
    }
    private int _Index;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Index
    {
      get { return _Index; }
      set { _Index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_AI_DIE")]
  public partial class CS_AI_DIE : global::ProtoBuf.IExtensible
  {
    public CS_AI_DIE() {}
    
    private ulong _KillerUID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"KillerUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong KillerUID
    {
      get { return _KillerUID; }
      set { _KillerUID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_AI_DIE")]
  public partial class SC_AI_DIE : global::ProtoBuf.IExtensible
  {
    public SC_AI_DIE() {}
    
    private ulong _EntityUID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"EntityUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong EntityUID
    {
      get { return _EntityUID; }
      set { _EntityUID = value; }
    }
    private ulong _KillerUID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"KillerUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong KillerUID
    {
      get { return _KillerUID; }
      set { _KillerUID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_AI_DAMAGE")]
  public partial class CS_AI_DAMAGE : global::ProtoBuf.IExtensible
  {
    public CS_AI_DAMAGE() {}
    
    private int _SkillId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SkillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SkillId
    {
      get { return _SkillId; }
      set { _SkillId = value; }
    }
    private int _SkillLevel;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SkillLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SkillLevel
    {
      get { return _SkillLevel; }
      set { _SkillLevel = value; }
    }
    private ulong _ParasiteUID = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ParasiteUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ParasiteUID
    {
      get { return _ParasiteUID; }
      set { _ParasiteUID = value; }
    }
    private ulong _TargetUID = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"TargetUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong TargetUID
    {
      get { return _TargetUID; }
      set { _TargetUID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_AI_DAMAGE")]
  public partial class SC_AI_DAMAGE : global::ProtoBuf.IExtensible
  {
    public SC_AI_DAMAGE() {}
    
    private ulong _EntityUID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"EntityUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong EntityUID
    {
      get { return _EntityUID; }
      set { _EntityUID = value; }
    }
    private int _SkillId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SkillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SkillId
    {
      get { return _SkillId; }
      set { _SkillId = value; }
    }
    private int _SkillLevel;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"SkillLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SkillLevel
    {
      get { return _SkillLevel; }
      set { _SkillLevel = value; }
    }
    private readonly global::System.Collections.Generic.List<SC_AI_DAMAGE.Victim> _Victims = new global::System.Collections.Generic.List<SC_AI_DAMAGE.Victim>();
    [global::ProtoBuf.ProtoMember(4, Name=@"Victims", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SC_AI_DAMAGE.Victim> Victims
    {
      get { return _Victims; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Victim")]
  public partial class Victim : global::ProtoBuf.IExtensible
  {
    public Victim() {}
    
    private ulong _UID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"UID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UID
    {
      get { return _UID; }
      set { _UID = value; }
    }
    private int _Blood;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Blood", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Blood
    {
      get { return _Blood; }
      set { _Blood = value; }
    }
    private int _Flag;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Flag
    {
      get { return _Flag; }
      set { _Flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_AI_POSITION")]
  public partial class CS_AI_POSITION : global::ProtoBuf.IExtensible
  {
    public CS_AI_POSITION() {}
    
    private float _DestX;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"DestX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DestX
    {
      get { return _DestX; }
      set { _DestX = value; }
    }
    private float _DestY;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"DestY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DestY
    {
      get { return _DestY; }
      set { _DestY = value; }
    }
    private float _DestZ;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"DestZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DestZ
    {
      get { return _DestZ; }
      set { _DestZ = value; }
    }
    private ulong _ParasiteUID = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ParasiteUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ParasiteUID
    {
      get { return _ParasiteUID; }
      set { _ParasiteUID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_AI_POSITION")]
  public partial class SC_AI_POSITION : global::ProtoBuf.IExtensible
  {
    public SC_AI_POSITION() {}
    
    private ulong _EntityUID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"EntityUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong EntityUID
    {
      get { return _EntityUID; }
      set { _EntityUID = value; }
    }
    private float _DestX;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"DestX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DestX
    {
      get { return _DestX; }
      set { _DestX = value; }
    }
    private float _DestY;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"DestY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DestY
    {
      get { return _DestY; }
      set { _DestY = value; }
    }
    private float _DestZ;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"DestZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DestZ
    {
      get { return _DestZ; }
      set { _DestZ = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_AI_PARASIZE")]
  public partial class SC_AI_PARASIZE : global::ProtoBuf.IExtensible
  {
    public SC_AI_PARASIZE() {}
    
    private ulong _ParasiteUID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ParasiteUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong ParasiteUID
    {
      get { return _ParasiteUID; }
      set { _ParasiteUID = value; }
    }
    private ulong _HostUID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"HostUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong HostUID
    {
      get { return _HostUID; }
      set { _HostUID = value; }
    }
    private ulong _TargetUID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"TargetUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong TargetUID
    {
      get { return _TargetUID; }
      set { _TargetUID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_AI_9GRID")]
  public partial class SC_AI_9GRID : global::ProtoBuf.IExtensible
  {
    public SC_AI_9GRID() {}
    
    private readonly global::System.Collections.Generic.List<SC_AI_9GRID.Grid> _Grids = new global::System.Collections.Generic.List<SC_AI_9GRID.Grid>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Grids", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SC_AI_9GRID.Grid> Grids
    {
      get { return _Grids; }
    }
  
    private int _rows;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"rows", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rows
    {
      get { return _rows; }
      set { _rows = value; }
    }
    private int _cols;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"cols", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cols
    {
      get { return _cols; }
      set { _cols = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Grid")]
  public partial class Grid : global::ProtoBuf.IExtensible
  {
    public Grid() {}
    
    private float _maxX;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"maxX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float maxX
    {
      get { return _maxX; }
      set { _maxX = value; }
    }
    private float _minX;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"minX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float minX
    {
      get { return _minX; }
      set { _minX = value; }
    }
    private float _maxZ;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"maxZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float maxZ
    {
      get { return _maxZ; }
      set { _maxZ = value; }
    }
    private float _minZ;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"minZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float minZ
    {
      get { return _minZ; }
      set { _minZ = value; }
    }
    private float _rowNumber;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"rowNumber", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rowNumber
    {
      get { return _rowNumber; }
      set { _rowNumber = value; }
    }
    private float _colNumber;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"colNumber", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float colNumber
    {
      get { return _colNumber; }
      set { _colNumber = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_AI_APPROACH")]
  public partial class CS_AI_APPROACH : global::ProtoBuf.IExtensible
  {
    public CS_AI_APPROACH() {}
    
    private float _DestX;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"DestX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DestX
    {
      get { return _DestX; }
      set { _DestX = value; }
    }
    private float _DestY;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"DestY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DestY
    {
      get { return _DestY; }
      set { _DestY = value; }
    }
    private float _DestZ;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"DestZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DestZ
    {
      get { return _DestZ; }
      set { _DestZ = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_AI_APPROACH")]
  public partial class SC_AI_APPROACH : global::ProtoBuf.IExtensible
  {
    public SC_AI_APPROACH() {}
    
    private float _DestX;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"DestX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DestX
    {
      get { return _DestX; }
      set { _DestX = value; }
    }
    private float _DestY;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"DestY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DestY
    {
      get { return _DestY; }
      set { _DestY = value; }
    }
    private float _DestZ;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"DestZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float DestZ
    {
      get { return _DestZ; }
      set { _DestZ = value; }
    }
    private ulong _EntityUID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"EntityUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong EntityUID
    {
      get { return _EntityUID; }
      set { _EntityUID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MSG_AI_ACTIONID")]
    public enum MSG_AI_ACTIONID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_AI_NONE", Value=0)]
      MSG_AI_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_AI_RUN", Value=1)]
      MSG_AI_RUN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_AI_ATTACK", Value=2)]
      MSG_AI_ATTACK = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_AI_TURNFACE", Value=3)]
      MSG_AI_TURNFACE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_AI_SWITCHWEAPON", Value=4)]
      MSG_AI_SWITCHWEAPON = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_AI_DIE", Value=5)]
      MSG_AI_DIE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_AI_DAMAGE", Value=6)]
      MSG_AI_DAMAGE = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_AI_POSITION", Value=7)]
      MSG_AI_POSITION = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_AI_PARASIZE", Value=8)]
      MSG_AI_PARASIZE = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_AI_9GRID", Value=9)]
      MSG_AI_9GRID = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_AI_APPROACH", Value=10)]
      MSG_AI_APPROACH = 10
    }
  
}