//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ChatMessage.proto
namespace ChatMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Char_SendChat")]
  public partial class CS_Char_SendChat : global::ProtoBuf.IExtensible
  {
    public CS_Char_SendChat() {}
    
    private uint _Channel;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Channel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Channel
    {
      get { return _Channel; }
      set { _Channel = value; }
    }
    private string _Content;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Char_SendChat")]
  public partial class SC_Char_SendChat : global::ProtoBuf.IExtensible
  {
    public SC_Char_SendChat() {}
    
    private uint _Channel;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Channel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Channel
    {
      get { return _Channel; }
      set { _Channel = value; }
    }
    private uint _SenderID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SenderID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SenderID
    {
      get { return _SenderID; }
      set { _SenderID = value; }
    }
    private string _SenderName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"SenderName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SenderName
    {
      get { return _SenderName; }
      set { _SenderName = value; }
    }
    private string _Content;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Char_ErrorResult")]
  public partial class SC_Char_ErrorResult : global::ProtoBuf.IExtensible
  {
    public SC_Char_ErrorResult() {}
    
    private uint _ShowMode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ShowMode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ShowMode
    {
      get { return _ShowMode; }
      set { _ShowMode = value; }
    }
    private uint _ResultCode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ResultCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ResultCode
    {
      get { return _ResultCode; }
      set { _ResultCode = value; }
    }
    private string _ErrorString = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ErrorString", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ErrorString
    {
      get { return _ErrorString; }
      set { _ErrorString = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Char_ShowPrizes")]
  public partial class SC_Char_ShowPrizes : global::ProtoBuf.IExtensible
  {
    public SC_Char_ShowPrizes() {}
    
    private uint _FormType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"FormType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FormType
    {
      get { return _FormType; }
      set { _FormType = value; }
    }
    private string _Prizes;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Prizes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Prizes
    {
      get { return _Prizes; }
      set { _Prizes = value; }
    }
    private string _Title;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Title
    {
      get { return _Title; }
      set { _Title = value; }
    }
    private string _Content;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MSG_CHAT_ACTIONID")]
    public enum MSG_CHAT_ACTIONID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CHAT_NONE", Value=0)]
      MSG_CHAT_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CHAT_SENDCHAT", Value=1)]
      MSG_CHAT_SENDCHAT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CHAT_ERRORRESULT", Value=2)]
      MSG_CHAT_ERRORRESULT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CHAT_SHOWPRIZES", Value=3)]
      MSG_CHAT_SHOWPRIZES = 3
    }
  
}