//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CountryMessage.proto
namespace CountryMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Country_KingList")]
  public partial class CS_Country_KingList : global::ProtoBuf.IExtensible
  {
    public CS_Country_KingList() {}
    
    private uint _Country;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Country", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Country
    {
      get { return _Country; }
      set { _Country = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Country_KingList")]
  public partial class SC_Country_KingList : global::ProtoBuf.IExtensible
  {
    public SC_Country_KingList() {}
    
    private uint _Country;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Country", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Country
    {
      get { return _Country; }
      set { _Country = value; }
    }
    private readonly global::System.Collections.Generic.List<SC_Country_KingList.KingData> _KingList = new global::System.Collections.Generic.List<SC_Country_KingList.KingData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"KingList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SC_Country_KingList.KingData> KingList
    {
      get { return _KingList; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KingData")]
  public partial class KingData : global::ProtoBuf.IExtensible
  {
    public KingData() {}
    
    private uint _Country;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Country", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Country
    {
      get { return _Country; }
      set { _Country = value; }
    }
    private uint _Officer;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Officer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Officer
    {
      get { return _Officer; }
      set { _Officer = value; }
    }
    private uint _ActorID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ActorID
    {
      get { return _ActorID; }
      set { _ActorID = value; }
    }
    private uint _WinNum;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"WinNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint WinNum
    {
      get { return _WinNum; }
      set { _WinNum = value; }
    }
    private uint _FailNum;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"FailNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FailNum
    {
      get { return _FailNum; }
      set { _FailNum = value; }
    }
    private uint _PreWinNum;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"PreWinNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PreWinNum
    {
      get { return _PreWinNum; }
      set { _PreWinNum = value; }
    }
    private uint _PreFailNum;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"PreFailNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PreFailNum
    {
      get { return _PreFailNum; }
      set { _PreFailNum = value; }
    }
    private string _ActorName;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"ActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActorName
    {
      get { return _ActorName; }
      set { _ActorName = value; }
    }
    private uint _Level;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private uint _Vocation;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"Vocation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Vocation
    {
      get { return _Vocation; }
      set { _Vocation = value; }
    }
    private uint _Power;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"Power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Power
    {
      get { return _Power; }
      set { _Power = value; }
    }
    private uint _Prestige;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"Prestige", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Prestige
    {
      get { return _Prestige; }
      set { _Prestige = value; }
    }
    private uint _Emblem;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"Emblem", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Emblem
    {
      get { return _Emblem; }
      set { _Emblem = value; }
    }
    private uint _VipLevel;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"VipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint VipLevel
    {
      get { return _VipLevel; }
      set { _VipLevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Country_KingWarList")]
  public partial class CS_Country_KingWarList : global::ProtoBuf.IExtensible
  {
    public CS_Country_KingWarList() {}
    
    private uint _Country;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Country", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Country
    {
      get { return _Country; }
      set { _Country = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Country_KingWarList")]
  public partial class SC_Country_KingWarList : global::ProtoBuf.IExtensible
  {
    public SC_Country_KingWarList() {}
    
    private uint _Country;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Country", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Country
    {
      get { return _Country; }
      set { _Country = value; }
    }
    private readonly global::System.Collections.Generic.List<SC_Country_KingWarList.KingWarData> _KingWarList = new global::System.Collections.Generic.List<SC_Country_KingWarList.KingWarData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"KingWarList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SC_Country_KingWarList.KingWarData> KingWarList
    {
      get { return _KingWarList; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KingWarData")]
  public partial class KingWarData : global::ProtoBuf.IExtensible
  {
    public KingWarData() {}
    
    private uint _SocietyID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyID
    {
      get { return _SocietyID; }
      set { _SocietyID = value; }
    }
    private string _SocietyName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SocietyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SocietyName
    {
      get { return _SocietyName; }
      set { _SocietyName = value; }
    }
    private uint _Vitality;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Vitality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Vitality
    {
      get { return _Vitality; }
      set { _Vitality = value; }
    }
    private uint _ActorID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ActorID
    {
      get { return _ActorID; }
      set { _ActorID = value; }
    }
    private string _ActorName;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"ActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActorName
    {
      get { return _ActorName; }
      set { _ActorName = value; }
    }
    private uint _MemCount;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"MemCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MemCount
    {
      get { return _MemCount; }
      set { _MemCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Country_SyncOfficer")]
  public partial class SC_Country_SyncOfficer : global::ProtoBuf.IExtensible
  {
    public SC_Country_SyncOfficer() {}
    
    private uint _Officer;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Officer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Officer
    {
      get { return _Officer; }
      set { _Officer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MSG_COUNTRY_ACTIONID")]
    public enum MSG_COUNTRY_ACTIONID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_COUNTRY_NONE", Value=0)]
      MSG_COUNTRY_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_COUNTRY_KINGLIST", Value=1)]
      MSG_COUNTRY_KINGLIST = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_COUNTRY_KINGWARLIST", Value=2)]
      MSG_COUNTRY_KINGWARLIST = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_COUNTRY_SYNOFFICER", Value=3)]
      MSG_COUNTRY_SYNOFFICER = 3
    }
  
}