//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FriendMessage.proto
namespace FriendMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendData")]
  public partial class FriendData : global::ProtoBuf.IExtensible
  {
    public FriendData() {}
    
    private uint _FriendID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"FriendID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FriendID
    {
      get { return _FriendID; }
      set { _FriendID = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private uint _RelationType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"RelationType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RelationType
    {
      get { return _RelationType; }
      set { _RelationType = value; }
    }
    private uint _Level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private uint _Vocation;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Vocation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Vocation
    {
      get { return _Vocation; }
      set { _Vocation = value; }
    }
    private uint _Power;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Power
    {
      get { return _Power; }
      set { _Power = value; }
    }
    private bool _IsOnLine;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"IsOnLine", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool IsOnLine
    {
      get { return _IsOnLine; }
      set { _IsOnLine = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OtherPlayerData")]
  public partial class OtherPlayerData : global::ProtoBuf.IExtensible
  {
    public OtherPlayerData() {}
    
    private uint _OtherPlayer;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"OtherPlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint OtherPlayer
    {
      get { return _OtherPlayer; }
      set { _OtherPlayer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Friend_GetFriendList")]
  public partial class CS_Friend_GetFriendList : global::ProtoBuf.IExtensible
  {
    public CS_Friend_GetFriendList() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Friend_GetFriendList")]
  public partial class SC_Friend_GetFriendList : global::ProtoBuf.IExtensible
  {
    public SC_Friend_GetFriendList() {}
    
    private uint _FriendNum;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"FriendNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FriendNum
    {
      get { return _FriendNum; }
      set { _FriendNum = value; }
    }
    private readonly global::System.Collections.Generic.List<FriendData> _FriendList = new global::System.Collections.Generic.List<FriendData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"FriendList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FriendData> FriendList
    {
      get { return _FriendList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Friend_Add")]
  public partial class CS_Friend_Add : global::ProtoBuf.IExtensible
  {
    public CS_Friend_Add() {}
    
    private string _ActorName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActorName
    {
      get { return _ActorName; }
      set { _ActorName = value; }
    }
    private uint _RelationType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RelationType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RelationType
    {
      get { return _RelationType; }
      set { _RelationType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Friend_Add")]
  public partial class SC_Friend_Add : global::ProtoBuf.IExtensible
  {
    public SC_Friend_Add() {}
    
    private uint _Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private uint _RelationType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RelationType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RelationType
    {
      get { return _RelationType; }
      set { _RelationType = value; }
    }
    private FriendData _FriendList;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"FriendList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public FriendData FriendList
    {
      get { return _FriendList; }
      set { _FriendList = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Friend_Delete")]
  public partial class CS_Friend_Delete : global::ProtoBuf.IExtensible
  {
    public CS_Friend_Delete() {}
    
    private uint _FriendID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"FriendID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FriendID
    {
      get { return _FriendID; }
      set { _FriendID = value; }
    }
    private uint _RelationType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RelationType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RelationType
    {
      get { return _RelationType; }
      set { _RelationType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Friend_Delete")]
  public partial class SC_Friend_Delete : global::ProtoBuf.IExtensible
  {
    public SC_Friend_Delete() {}
    
    private uint _FriendID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"FriendID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FriendID
    {
      get { return _FriendID; }
      set { _FriendID = value; }
    }
    private uint _RelationType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RelationType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RelationType
    {
      get { return _RelationType; }
      set { _RelationType = value; }
    }
    private uint _Result;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Friend_SendChat")]
  public partial class CS_Friend_SendChat : global::ProtoBuf.IExtensible
  {
    public CS_Friend_SendChat() {}
    
    private uint _FriendID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"FriendID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FriendID
    {
      get { return _FriendID; }
      set { _FriendID = value; }
    }
    private string _Content;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Friend_SendChat")]
  public partial class SC_Friend_SendChat : global::ProtoBuf.IExtensible
  {
    public SC_Friend_SendChat() {}
    
    private FriendData _FriendData;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"FriendData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public FriendData FriendData
    {
      get { return _FriendData; }
      set { _FriendData = value; }
    }
    private string _Content;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Friend_SendChatReturn")]
  public partial class SC_Friend_SendChatReturn : global::ProtoBuf.IExtensible
  {
    public SC_Friend_SendChatReturn() {}
    
    private uint _Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private uint _FriendID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"FriendID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FriendID
    {
      get { return _FriendID; }
      set { _FriendID = value; }
    }
    private string _Content;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Friend_Recommend")]
  public partial class CS_Friend_Recommend : global::ProtoBuf.IExtensible
  {
    public CS_Friend_Recommend() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Friend_Recommend")]
  public partial class SC_Friend_Recommend : global::ProtoBuf.IExtensible
  {
    public SC_Friend_Recommend() {}
    
    private uint _FriendNum;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"FriendNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FriendNum
    {
      get { return _FriendNum; }
      set { _FriendNum = value; }
    }
    private readonly global::System.Collections.Generic.List<FriendData> _FriendList = new global::System.Collections.Generic.List<FriendData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"FriendList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FriendData> FriendList
    {
      get { return _FriendList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Other_Player")]
  public partial class CS_Other_Player : global::ProtoBuf.IExtensible
  {
    public CS_Other_Player() {}
    
    private uint _OtherPlayerID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"OtherPlayerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint OtherPlayerID
    {
      get { return _OtherPlayerID; }
      set { _OtherPlayerID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_ChatOffline_List")]
  public partial class SC_ChatOffline_List : global::ProtoBuf.IExtensible
  {
    public SC_ChatOffline_List() {}
    
    private uint _ChatNum;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ChatNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ChatNum
    {
      get { return _ChatNum; }
      set { _ChatNum = value; }
    }
    private readonly global::System.Collections.Generic.List<SC_ChatOffline_List.ChatofflineData> _chatofflineData = new global::System.Collections.Generic.List<SC_ChatOffline_List.ChatofflineData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"chatofflineData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SC_ChatOffline_List.ChatofflineData> chatofflineData
    {
      get { return _chatofflineData; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatofflineData")]
  public partial class ChatofflineData : global::ProtoBuf.IExtensible
  {
    public ChatofflineData() {}
    
    private uint _SendActorID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SendActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SendActorID
    {
      get { return _SendActorID; }
      set { _SendActorID = value; }
    }
    private string _SendActorName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SendActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SendActorName
    {
      get { return _SendActorName; }
      set { _SendActorName = value; }
    }
    private uint _SendTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"SendTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SendTime
    {
      get { return _SendTime; }
      set { _SendTime = value; }
    }
    private string _TalkContent;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"TalkContent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TalkContent
    {
      get { return _TalkContent; }
      set { _TalkContent = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Delete_ChatOffline_List")]
  public partial class CS_Delete_ChatOffline_List : global::ProtoBuf.IExtensible
  {
    public CS_Delete_ChatOffline_List() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MSG_FRIEND_ACTIONID")]
    public enum MSG_FRIEND_ACTIONID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_FRIEND_NONE", Value=0)]
      MSG_FRIEND_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_FRIEND_GETLIST", Value=1)]
      MSG_FRIEND_GETLIST = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_FRIEND_ADD", Value=2)]
      MSG_FRIEND_ADD = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_FRIEND_DELETE", Value=3)]
      MSG_FRIEND_DELETE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_FRIEND_SENDCHAT", Value=4)]
      MSG_FRIEND_SENDCHAT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_FRIEND_SENDCHATRETURN", Value=5)]
      MSG_FRIEND_SENDCHATRETURN = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_FRIEND_RECOMMEND", Value=6)]
      MSG_FRIEND_RECOMMEND = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_OTHERPLAYER_INFO", Value=7)]
      MSG_OTHERPLAYER_INFO = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_CHATOFFLINE_LIST", Value=8)]
      MSG_CHATOFFLINE_LIST = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_DELETE_CHATOFFLINE_LIST", Value=9)]
      MSG_DELETE_CHATOFFLINE_LIST = 9
    }
  
}