//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LoginMessage.proto
namespace LoginMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CL_Login_Register")]
  public partial class CL_Login_Register : global::ProtoBuf.IExtensible
  {
    public CL_Login_Register() {}
    
    private string _UserName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string UserName
    {
      get { return _UserName; }
      set { _UserName = value; }
    }
    private string _Password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private string _RegisterOS;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"RegisterOS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RegisterOS
    {
      get { return _RegisterOS; }
      set { _RegisterOS = value; }
    }
    private string _RegisterHW;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"RegisterHW", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RegisterHW
    {
      get { return _RegisterHW; }
      set { _RegisterHW = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LC_Login_Register")]
  public partial class LC_Login_Register : global::ProtoBuf.IExtensible
  {
    public LC_Login_Register() {}
    
    private uint _Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CL_Login_LoginUser")]
  public partial class CL_Login_LoginUser : global::ProtoBuf.IExtensible
  {
    public CL_Login_LoginUser() {}
    
    private string _UserName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string UserName
    {
      get { return _UserName; }
      set { _UserName = value; }
    }
    private string _Password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private string _LoginOS;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"LoginOS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string LoginOS
    {
      get { return _LoginOS; }
      set { _LoginOS = value; }
    }
    private string _LoginHW;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"LoginHW", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string LoginHW
    {
      get { return _LoginHW; }
      set { _LoginHW = value; }
    }
    private uint _LoginID;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"LoginID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LoginID
    {
      get { return _LoginID; }
      set { _LoginID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LC_Login_LoginUser")]
  public partial class LC_Login_LoginUser : global::ProtoBuf.IExtensible
  {
    public LC_Login_LoginUser() {}
    
    private uint _Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private readonly global::System.Collections.Generic.List<LC_Login_LoginUser.ActorInfo> _ActorList = new global::System.Collections.Generic.List<LC_Login_LoginUser.ActorInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"ActorList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<LC_Login_LoginUser.ActorInfo> ActorList
    {
      get { return _ActorList; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActorInfo")]
  public partial class ActorInfo : global::ProtoBuf.IExtensible
  {
    public ActorInfo() {}
    
    private uint _ActorID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ActorID
    {
      get { return _ActorID; }
      set { _ActorID = value; }
    }
    private string _ActorName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActorName
    {
      get { return _ActorName; }
      set { _ActorName = value; }
    }
    private uint _Level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private uint _Vocation;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Vocation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Vocation
    {
      get { return _Vocation; }
      set { _Vocation = value; }
    }
    private uint _Country;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Country", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Country
    {
      get { return _Country; }
      set { _Country = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CL_Login_CreateActor")]
  public partial class CL_Login_CreateActor : global::ProtoBuf.IExtensible
  {
    public CL_Login_CreateActor() {}
    
    private string _ActorName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActorName
    {
      get { return _ActorName; }
      set { _ActorName = value; }
    }
    private string _CreateOS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"CreateOS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string CreateOS
    {
      get { return _CreateOS; }
      set { _CreateOS = value; }
    }
    private string _CreateHW;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"CreateHW", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string CreateHW
    {
      get { return _CreateHW; }
      set { _CreateHW = value; }
    }
    private uint _Vocation;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Vocation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Vocation
    {
      get { return _Vocation; }
      set { _Vocation = value; }
    }
    private uint _Country;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Country", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Country
    {
      get { return _Country; }
      set { _Country = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LC_Login_CreateActor")]
  public partial class LC_Login_CreateActor : global::ProtoBuf.IExtensible
  {
    public LC_Login_CreateActor() {}
    
    private uint _Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private LC_Login_CreateActor.ActorInfo _NewActor = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"NewActor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public LC_Login_CreateActor.ActorInfo NewActor
    {
      get { return _NewActor; }
      set { _NewActor = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActorInfo")]
  public partial class ActorInfo : global::ProtoBuf.IExtensible
  {
    public ActorInfo() {}
    
    private uint _ActorID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ActorID
    {
      get { return _ActorID; }
      set { _ActorID = value; }
    }
    private string _ActorName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActorName
    {
      get { return _ActorName; }
      set { _ActorName = value; }
    }
    private uint _Level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private uint _Vocation;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Vocation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Vocation
    {
      get { return _Vocation; }
      set { _Vocation = value; }
    }
    private uint _Country;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Country", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Country
    {
      get { return _Country; }
      set { _Country = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CL_Login_DeleteActor")]
  public partial class CL_Login_DeleteActor : global::ProtoBuf.IExtensible
  {
    public CL_Login_DeleteActor() {}
    
    private uint _ActorID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ActorID
    {
      get { return _ActorID; }
      set { _ActorID = value; }
    }
    private string _ActorName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActorName
    {
      get { return _ActorName; }
      set { _ActorName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LC_Login_DeleteActor")]
  public partial class LC_Login_DeleteActor : global::ProtoBuf.IExtensible
  {
    public LC_Login_DeleteActor() {}
    
    private uint _Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private uint _ActorID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ActorID
    {
      get { return _ActorID; }
      set { _ActorID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CL_Login_SeleteActor")]
  public partial class CL_Login_SeleteActor : global::ProtoBuf.IExtensible
  {
    public CL_Login_SeleteActor() {}
    
    private uint _ActorID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ActorID
    {
      get { return _ActorID; }
      set { _ActorID = value; }
    }
    private string _ActorName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActorName
    {
      get { return _ActorName; }
      set { _ActorName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LC_Login_SeleteActor")]
  public partial class LC_Login_SeleteActor : global::ProtoBuf.IExtensible
  {
    public LC_Login_SeleteActor() {}
    
    private uint _Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LS_Login_SeleteActor")]
  public partial class LS_Login_SeleteActor : global::ProtoBuf.IExtensible
  {
    public LS_Login_SeleteActor() {}
    
    private uint _ClientID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ClientID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ClientID
    {
      get { return _ClientID; }
      set { _ClientID = value; }
    }
    private uint _UserID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }
    private uint _ActorID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ActorID
    {
      get { return _ActorID; }
      set { _ActorID = value; }
    }
    private string _UserName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"UserName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string UserName
    {
      get { return _UserName; }
      set { _UserName = value; }
    }
    private string _ActorName;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"ActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActorName
    {
      get { return _ActorName; }
      set { _ActorName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CL_Login_Reconnect")]
  public partial class CL_Login_Reconnect : global::ProtoBuf.IExtensible
  {
    public CL_Login_Reconnect() {}
    
    private string _UserName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string UserName
    {
      get { return _UserName; }
      set { _UserName = value; }
    }
    private string _Password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private uint _LoginID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"LoginID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LoginID
    {
      get { return _LoginID; }
      set { _LoginID = value; }
    }
    private MSG_LOGIN_PLAYER_STATE _State;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"State", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MSG_LOGIN_PLAYER_STATE State
    {
      get { return _State; }
      set { _State = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CL_Login_Reconnect_UC")]
  public partial class CL_Login_Reconnect_UC : global::ProtoBuf.IExtensible
  {
    public CL_Login_Reconnect_UC() {}
    
    private string _Sid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Sid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Sid
    {
      get { return _Sid; }
      set { _Sid = value; }
    }
    private uint _LoginID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"LoginID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LoginID
    {
      get { return _LoginID; }
      set { _LoginID = value; }
    }
    private MSG_LOGIN_PLAYER_STATE _State;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"State", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MSG_LOGIN_PLAYER_STATE State
    {
      get { return _State; }
      set { _State = value; }
    }
    private string _SidMd5;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"SidMd5", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SidMd5
    {
      get { return _SidMd5; }
      set { _SidMd5 = value; }
    }
    private int _DebugMode;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"DebugMode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int DebugMode
    {
      get { return _DebugMode; }
      set { _DebugMode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LC_Login_Reconnect")]
  public partial class LC_Login_Reconnect : global::ProtoBuf.IExtensible
  {
    public LC_Login_Reconnect() {}
    
    private uint _Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SL_Login_AddReconnect")]
  public partial class SL_Login_AddReconnect : global::ProtoBuf.IExtensible
  {
    public SL_Login_AddReconnect() {}
    
    private uint _UserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }
    private uint _ClientID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ClientID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ClientID
    {
      get { return _ClientID; }
      set { _ClientID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SL_Login_DelReconnect")]
  public partial class SL_Login_DelReconnect : global::ProtoBuf.IExtensible
  {
    public SL_Login_DelReconnect() {}
    
    private uint _UserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LS_Login_Reconnect")]
  public partial class LS_Login_Reconnect : global::ProtoBuf.IExtensible
  {
    public LS_Login_Reconnect() {}
    
    private uint _UserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }
    private uint _NewClientID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"NewClientID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint NewClientID
    {
      get { return _NewClientID; }
      set { _NewClientID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CL_Login_LoginUser_UC")]
  public partial class CL_Login_LoginUser_UC : global::ProtoBuf.IExtensible
  {
    public CL_Login_LoginUser_UC() {}
    
    private uint _ZoneID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ZoneID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ZoneID
    {
      get { return _ZoneID; }
      set { _ZoneID = value; }
    }
    private string _Sid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Sid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Sid
    {
      get { return _Sid; }
      set { _Sid = value; }
    }
    private string _SidMd5;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"SidMd5", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SidMd5
    {
      get { return _SidMd5; }
      set { _SidMd5 = value; }
    }
    private int _DebugMode;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"DebugMode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int DebugMode
    {
      get { return _DebugMode; }
      set { _DebugMode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CL_Login_SwitchActor")]
  public partial class CL_Login_SwitchActor : global::ProtoBuf.IExtensible
  {
    public CL_Login_SwitchActor() {}
    
    private uint _ActorID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ActorID
    {
      get { return _ActorID; }
      set { _ActorID = value; }
    }
    private string _ActorName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActorName
    {
      get { return _ActorName; }
      set { _ActorName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LC_Login_SwitchActor")]
  public partial class LC_Login_SwitchActor : global::ProtoBuf.IExtensible
  {
    public LC_Login_SwitchActor() {}
    
    private uint _Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CL_Login_LoginUser_MI")]
  public partial class CL_Login_LoginUser_MI : global::ProtoBuf.IExtensible
  {
    public CL_Login_LoginUser_MI() {}
    
    private uint _ZoneID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ZoneID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ZoneID
    {
      get { return _ZoneID; }
      set { _ZoneID = value; }
    }
    private long _Uid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long Uid
    {
      get { return _Uid; }
      set { _Uid = value; }
    }
    private string _Sid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Sid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Sid
    {
      get { return _Sid; }
      set { _Sid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CL_Login_Reconnect_MI")]
  public partial class CL_Login_Reconnect_MI : global::ProtoBuf.IExtensible
  {
    public CL_Login_Reconnect_MI() {}
    
    private uint _ZoneID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ZoneID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ZoneID
    {
      get { return _ZoneID; }
      set { _ZoneID = value; }
    }
    private long _Uid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long Uid
    {
      get { return _Uid; }
      set { _Uid = value; }
    }
    private string _Sid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Sid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Sid
    {
      get { return _Sid; }
      set { _Sid = value; }
    }
    private MSG_LOGIN_PLAYER_STATE _State;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"State", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MSG_LOGIN_PLAYER_STATE State
    {
      get { return _State; }
      set { _State = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CL_Login_LoginUser_ZS")]
  public partial class CL_Login_LoginUser_ZS : global::ProtoBuf.IExtensible
  {
    public CL_Login_LoginUser_ZS() {}
    
    private uint _ZoneID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ZoneID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ZoneID
    {
      get { return _ZoneID; }
      set { _ZoneID = value; }
    }
    private string _Uid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Uid
    {
      get { return _Uid; }
      set { _Uid = value; }
    }
    private string _Sid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Sid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Sid
    {
      get { return _Sid; }
      set { _Sid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CL_Login_Reconnect_ZS")]
  public partial class CL_Login_Reconnect_ZS : global::ProtoBuf.IExtensible
  {
    public CL_Login_Reconnect_ZS() {}
    
    private uint _ZoneID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ZoneID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ZoneID
    {
      get { return _ZoneID; }
      set { _ZoneID = value; }
    }
    private string _Uid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Uid
    {
      get { return _Uid; }
      set { _Uid = value; }
    }
    private string _Sid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Sid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Sid
    {
      get { return _Sid; }
      set { _Sid = value; }
    }
    private MSG_LOGIN_PLAYER_STATE _State;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"State", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MSG_LOGIN_PLAYER_STATE State
    {
      get { return _State; }
      set { _State = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CL_Login_LogoutUser")]
  public partial class CL_Login_LogoutUser : global::ProtoBuf.IExtensible
  {
    public CL_Login_LogoutUser() {}
    
    private uint _ActorID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ActorID
    {
      get { return _ActorID; }
      set { _ActorID = value; }
    }
    private string _ActorName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActorName
    {
      get { return _ActorName; }
      set { _ActorName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LC_Login_LogoutUser")]
  public partial class LC_Login_LogoutUser : global::ProtoBuf.IExtensible
  {
    public LC_Login_LogoutUser() {}
    
    private uint _Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LS_Login_LogoutUser")]
  public partial class LS_Login_LogoutUser : global::ProtoBuf.IExtensible
  {
    public LS_Login_LogoutUser() {}
    
    private uint _ClientID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ClientID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ClientID
    {
      get { return _ClientID; }
      set { _ClientID = value; }
    }
    private uint _UserID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }
    private uint _ActorID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ActorID
    {
      get { return _ActorID; }
      set { _ActorID = value; }
    }
    private string _UserName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"UserName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string UserName
    {
      get { return _UserName; }
      set { _UserName = value; }
    }
    private string _ActorName;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"ActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActorName
    {
      get { return _ActorName; }
      set { _ActorName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MSG_LOGIN_ACTIONID")]
    public enum MSG_LOGIN_ACTIONID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_NONE", Value=0)]
      MSG_LOGIN_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_REGISTER", Value=1)]
      MSG_LOGIN_REGISTER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_LOGINUSER", Value=2)]
      MSG_LOGIN_LOGINUSER = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_CREATEACTOR", Value=3)]
      MSG_LOGIN_CREATEACTOR = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_DELETEACTOR", Value=4)]
      MSG_LOGIN_DELETEACTOR = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_SELETEACTOR", Value=5)]
      MSG_LOGIN_SELETEACTOR = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_RECONNECT", Value=6)]
      MSG_LOGIN_RECONNECT = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_ADD_RECONNECT", Value=7)]
      MSG_LOGIN_ADD_RECONNECT = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_DEL_RECONNECT", Value=8)]
      MSG_LOGIN_DEL_RECONNECT = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_LOGINUSER_UC", Value=9)]
      MSG_LOGIN_LOGINUSER_UC = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_SWITCHACTOR", Value=10)]
      MSG_LOGIN_SWITCHACTOR = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_RECONNECT_UC", Value=11)]
      MSG_LOGIN_RECONNECT_UC = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_LOGINUSER_MI", Value=12)]
      MSG_LOGIN_LOGINUSER_MI = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_RECONNECT_MI", Value=13)]
      MSG_LOGIN_RECONNECT_MI = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_LOGINUSER_ZS", Value=14)]
      MSG_LOGIN_LOGINUSER_ZS = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_RECONNECT_ZS", Value=15)]
      MSG_LOGIN_RECONNECT_ZS = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_LOGOUTUSER", Value=16)]
      MSG_LOGIN_LOGOUTUSER = 16
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MSG_LOGIN_PLAYER_STATE")]
    public enum MSG_LOGIN_PLAYER_STATE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_PLAYER_STATE_UNKNOWN", Value=0)]
      MSG_LOGIN_PLAYER_STATE_UNKNOWN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_PLAYER_STATE_CREATE_ACTOR", Value=1)]
      MSG_LOGIN_PLAYER_STATE_CREATE_ACTOR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_PLAYER_STATE_SELECT_ACTOR", Value=2)]
      MSG_LOGIN_PLAYER_STATE_SELECT_ACTOR = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_LOGIN_PLAYER_STATE_PLAYING", Value=3)]
      MSG_LOGIN_PLAYER_STATE_PLAYING = 3
    }
  
}