//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: input/LuaMessage.proto
namespace LuaMessage
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CS_Lua_RunRequest")]
    public partial class CS_Lua_RunRequest : global::ProtoBuf.IExtensible
    {
        public CS_Lua_RunRequest() { }

        private uint _opcode;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"opcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public uint opcode
        {
            get { return _opcode; }
            set { _opcode = value; }
        }
        private byte[] _parameters = null;
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"parameters", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public byte[] parameters
        {
            get { return _parameters; }
            set { _parameters = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"SC_Lua_RunRequest")]
    public partial class SC_Lua_RunRequest : global::ProtoBuf.IExtensible
    {
        public SC_Lua_RunRequest() { }

        private uint _opcode;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"opcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public uint opcode
        {
            get { return _opcode; }
            set { _opcode = value; }
        }
        private byte[] _parameters = null;
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"parameters", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public byte[] parameters
        {
            get { return _parameters; }
            set { _parameters = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Position")]
    public partial class Position : global::ProtoBuf.IExtensible
    {
        public Position() { }

        private byte[] _entityid;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"entityid", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public byte[] entityid
        {
            get { return _entityid; }
            set { _entityid = value; }
        }
        private float _DestX;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"DestX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float DestX
        {
            get { return _DestX; }
            set { _DestX = value; }
        }
        private float _DestY;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"DestY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float DestY
        {
            get { return _DestY; }
            set { _DestY = value; }
        }
        private float _DestZ;
        [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name = @"DestZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float DestZ
        {
            get { return _DestZ; }
            set { _DestZ = value; }
        }
        private float _Orientation;
        [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name = @"Orientation", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float Orientation
        {
            get { return _Orientation; }
            set { _Orientation = value; }
        }
        private float _Speed;
        [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name = @"Speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float Speed
        {
            get { return _Speed; }
            set { _Speed = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CS_CLIENT_MOVE")]
    public partial class CS_CLIENT_MOVE : global::ProtoBuf.IExtensible
    {
        public CS_CLIENT_MOVE() { }

        private Position _MyPostion;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"MyPostion", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Position MyPostion
        {
            get { return _MyPostion; }
            set { _MyPostion = value; }
        }
        private ulong _clienttime;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"clienttime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public ulong clienttime
        {
            get { return _clienttime; }
            set { _clienttime = value; }
        }
        private uint _SceneID;
        [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name = @"SceneID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public uint SceneID
        {
            get { return _SceneID; }
            set { _SceneID = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"SC_MOVE_SYNC")]
    public partial class SC_MOVE_SYNC : global::ProtoBuf.IExtensible
    {
        public SC_MOVE_SYNC() { }

        private Position _SyncPostion;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"SyncPostion", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Position SyncPostion
        {
            get { return _SyncPostion; }
            set { _SyncPostion = value; }
        }
        private ulong _servertime;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"servertime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public ulong servertime
        {
            get { return _servertime; }
            set { _servertime = value; }
        }
        private uint _SceneID;
        [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name = @"SceneID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public uint SceneID
        {
            get { return _SceneID; }
            set { _SceneID = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CS_STOP_MOVE")]
    public partial class CS_STOP_MOVE : global::ProtoBuf.IExtensible
    {
        public CS_STOP_MOVE() { }

        private Position _MyPostion;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"MyPostion", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public Position MyPostion
        {
            get { return _MyPostion; }
            set { _MyPostion = value; }
        }
        private ulong _clienttime;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"clienttime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public ulong clienttime
        {
            get { return _clienttime; }
            set { _clienttime = value; }
        }
        private uint _SceneID;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"SceneID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public uint SceneID
        {
            get { return _SceneID; }
            set { _SceneID = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"SC_STOP_MOVE_SYNC")]
    public partial class SC_STOP_MOVE_SYNC : global::ProtoBuf.IExtensible
    {
        public SC_STOP_MOVE_SYNC() { }

        private readonly global::System.Collections.Generic.List<Position> _SyncPostion = new global::System.Collections.Generic.List<Position>();
        [global::ProtoBuf.ProtoMember(1, Name = @"SyncPostion", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<Position> SyncPostion
        {
            get { return _SyncPostion; }
        }

        private ulong _servertime;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"servertime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public ulong servertime
        {
            get { return _servertime; }
            set { _servertime = value; }
        }
        private uint _SceneID;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"SceneID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public uint SceneID
        {
            get { return _SceneID; }
            set { _SceneID = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CS_FORCE_MOVE")]
    public partial class CS_FORCE_MOVE : global::ProtoBuf.IExtensible
    {
        public CS_FORCE_MOVE() { }

        private byte[] _entityid;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"entityid", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public byte[] entityid
        {
            get { return _entityid; }
            set { _entityid = value; }
        }
        private float _DestX;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"DestX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float DestX
        {
            get { return _DestX; }
            set { _DestX = value; }
        }
        private float _DestY;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"DestY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float DestY
        {
            get { return _DestY; }
            set { _DestY = value; }
        }
        private float _DestZ;
        [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name = @"DestZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float DestZ
        {
            get { return _DestZ; }
            set { _DestZ = value; }
        }
        private uint _SceneID;
        [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name = @"SceneID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public uint SceneID
        {
            get { return _SceneID; }
            set { _SceneID = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"SC_FORCE_MOVE")]
    public partial class SC_FORCE_MOVE : global::ProtoBuf.IExtensible
    {
        public SC_FORCE_MOVE() { }

        private byte[] _entityid;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"entityid", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public byte[] entityid
        {
            get { return _entityid; }
            set { _entityid = value; }
        }
        private float _DestX;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"DestX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float DestX
        {
            get { return _DestX; }
            set { _DestX = value; }
        }
        private float _DestY;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"DestY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float DestY
        {
            get { return _DestY; }
            set { _DestY = value; }
        }
        private float _DestZ;
        [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name = @"DestZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float DestZ
        {
            get { return _DestZ; }
            set { _DestZ = value; }
        }
        private uint _SceneID;
        [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name = @"SceneID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public uint SceneID
        {
            get { return _SceneID; }
            set { _SceneID = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CS_TURN_DIRECTION")]
    public partial class CS_TURN_DIRECTION : global::ProtoBuf.IExtensible
    {
        public CS_TURN_DIRECTION() { }

        private byte[] _entityid;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"entityid", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public byte[] entityid
        {
            get { return _entityid; }
            set { _entityid = value; }
        }
        private float _DestX;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"DestX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float DestX
        {
            get { return _DestX; }
            set { _DestX = value; }
        }
        private float _DestY;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"DestY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float DestY
        {
            get { return _DestY; }
            set { _DestY = value; }
        }
        private float _DestZ;
        [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name = @"DestZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float DestZ
        {
            get { return _DestZ; }
            set { _DestZ = value; }
        }
        private float _Direction;
        [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name = @"Direction", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float Direction
        {
            get { return _Direction; }
            set { _Direction = value; }
        }
        private uint _SceneID;
        [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name = @"SceneID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public uint SceneID
        {
            get { return _SceneID; }
            set { _SceneID = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"SC_TURN_DIRECTION")]
    public partial class SC_TURN_DIRECTION : global::ProtoBuf.IExtensible
    {
        public SC_TURN_DIRECTION() { }

        private byte[] _entityid;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"entityid", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public byte[] entityid
        {
            get { return _entityid; }
            set { _entityid = value; }
        }
        private float _DestX;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"DestX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float DestX
        {
            get { return _DestX; }
            set { _DestX = value; }
        }
        private float _DestY;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"DestY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float DestY
        {
            get { return _DestY; }
            set { _DestY = value; }
        }
        private float _DestZ;
        [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name = @"DestZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float DestZ
        {
            get { return _DestZ; }
            set { _DestZ = value; }
        }
        private float _Direction;
        [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name = @"Direction", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float Direction
        {
            get { return _Direction; }
            set { _Direction = value; }
        }
        private uint _SceneID;
        [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name = @"SceneID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public uint SceneID
        {
            get { return _SceneID; }
            set { _SceneID = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"SC_CREATE_ENTITY")]
    public partial class SC_CREATE_ENTITY : global::ProtoBuf.IExtensible
    {
        public SC_CREATE_ENTITY() { }

        private uint _SceneID;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"SceneID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public uint SceneID
        {
            get { return _SceneID; }
            set { _SceneID = value; }
        }
        private readonly global::System.Collections.Generic.List<SC_CREATE_ENTITY.Entity> _EntitiesCreate = new global::System.Collections.Generic.List<SC_CREATE_ENTITY.Entity>();
        [global::ProtoBuf.ProtoMember(2, Name = @"EntitiesCreate", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<SC_CREATE_ENTITY.Entity> EntitiesCreate
        {
            get { return _EntitiesCreate; }
        }

        [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Entity")]
        public partial class Entity : global::ProtoBuf.IExtensible
        {
            public Entity() { }

            private byte[] _EntityID;
            [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"EntityID", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public byte[] EntityID
            {
                get { return _EntityID; }
                set { _EntityID = value; }
            }
            private byte[] _EntityInfo;
            [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"EntityInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public byte[] EntityInfo
            {
                get { return _EntityInfo; }
                set { _EntityInfo = value; }
            }
            private Position _EntityPos;
            [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"EntityPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
            public Position EntityPos
            {
                get { return _EntityPos; }
                set { _EntityPos = value; }
            }
            private global::ProtoBuf.IExtension extensionObject;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"SC_DESTROY_ENTITY")]
    public partial class SC_DESTROY_ENTITY : global::ProtoBuf.IExtensible
    {
        public SC_DESTROY_ENTITY() { }

        private uint _SceneID;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"SceneID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public uint SceneID
        {
            get { return _SceneID; }
            set { _SceneID = value; }
        }
        private readonly global::System.Collections.Generic.List<byte[]> _EntitiesDestroy = new global::System.Collections.Generic.List<byte[]>();
        [global::ProtoBuf.ProtoMember(2, Name = @"EntitiesDestroy", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<byte[]> EntitiesDestroy
        {
            get { return _EntitiesDestroy; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CS_PING")]
    public partial class CS_PING : global::ProtoBuf.IExtensible
    {
        public CS_PING() { }

        private ulong _clienttime;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"clienttime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public ulong clienttime
        {
            get { return _clienttime; }
            set { _clienttime = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"SC_PING_BACK")]
    public partial class SC_PING_BACK : global::ProtoBuf.IExtensible
    {
        public SC_PING_BACK() { }

        private ulong _clienttime;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"clienttime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public ulong clienttime
        {
            get { return _clienttime; }
            set { _clienttime = value; }
        }
        private ulong _servertime;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"servertime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public ulong servertime
        {
            get { return _servertime; }
            set { _servertime = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CS_PING_BACK_BACK")]
    public partial class CS_PING_BACK_BACK : global::ProtoBuf.IExtensible
    {
        public CS_PING_BACK_BACK() { }

        private ulong _clienttime;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"clienttime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public ulong clienttime
        {
            get { return _clienttime; }
            set { _clienttime = value; }
        }
        private ulong _servertime;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"servertime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public ulong servertime
        {
            get { return _servertime; }
            set { _servertime = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ConnectServerRequest")]
    public partial class ConnectServerRequest : global::ProtoBuf.IExtensible
    {
        public ConnectServerRequest() { }

        private ConnectServerRequest.RequestType _type;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public ConnectServerRequest.RequestType type
        {
            get { return _type; }
            set { _type = value; }
        }
        private byte[] _deviceid;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"deviceid", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public byte[] deviceid
        {
            get { return _deviceid; }
            set { _deviceid = value; }
        }
        private byte[] _entityid = null;
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"entityid", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public byte[] entityid
        {
            get { return _entityid; }
            set { _entityid = value; }
        }
        private byte[] _authmsg = null;
        [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name = @"authmsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public byte[] authmsg
        {
            get { return _authmsg; }
            set { _authmsg = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"RequestType")]
        public enum RequestType
        {

            [global::ProtoBuf.ProtoEnum(Name = @"NEW_CONNECTION", Value = 0)]
            NEW_CONNECTION = 0,

            [global::ProtoBuf.ProtoEnum(Name = @"RE_CONNECTION", Value = 1)]
            RE_CONNECTION = 1
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"ConnectServerReply")]
    public partial class ConnectServerReply : global::ProtoBuf.IExtensible
    {
        public ConnectServerReply() { }

        private ConnectServerReply.ReplyType _type;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public ConnectServerReply.ReplyType type
        {
            get { return _type; }
            set { _type = value; }
        }
        private byte[] _extramsg = null;
        [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name = @"extramsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue(null)]
        public byte[] extramsg
        {
            get { return _extramsg; }
            set { _extramsg = value; }
        }
        [global::ProtoBuf.ProtoContract(Name = @"ReplyType")]
        public enum ReplyType
        {

            [global::ProtoBuf.ProtoEnum(Name = @"BUSY", Value = 0)]
            BUSY = 0,

            [global::ProtoBuf.ProtoEnum(Name = @"CONNECTED", Value = 1)]
            CONNECTED = 1,

            [global::ProtoBuf.ProtoEnum(Name = @"RECONNECT_SUCCEEDED", Value = 2)]
            RECONNECT_SUCCEEDED = 2,

            [global::ProtoBuf.ProtoEnum(Name = @"RECONNECT_FAILED", Value = 3)]
            RECONNECT_FAILED = 3,

            [global::ProtoBuf.ProtoEnum(Name = @"FORBIDDEN", Value = 4)]
            FORBIDDEN = 4,

            [global::ProtoBuf.ProtoEnum(Name = @"MAX_CONNECTION", Value = 5)]
            MAX_CONNECTION = 5
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CS_RUN_STATE_CHANGE")]
    public partial class CS_RUN_STATE_CHANGE : global::ProtoBuf.IExtensible
    {
        public CS_RUN_STATE_CHANGE() { }

        private byte[] _entityid;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"entityid", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public byte[] entityid
        {
            get { return _entityid; }
            set { _entityid = value; }
        }
        private bool _isrunning;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"isrunning", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public bool isrunning
        {
            get { return _isrunning; }
            set { _isrunning = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CS_ROTATE_CHANGE")]
    public partial class CS_ROTATE_CHANGE : global::ProtoBuf.IExtensible
    {
        public CS_ROTATE_CHANGE() { }

        private byte[] _entityid;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"entityid", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public byte[] entityid
        {
            get { return _entityid; }
            set { _entityid = value; }
        }
        private float _rotationY;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"rotationY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float rotationY
        {
            get { return _rotationY; }
            set { _rotationY = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"SC_RUN_STATE_CHANGE")]
    public partial class SC_RUN_STATE_CHANGE : global::ProtoBuf.IExtensible
    {
        public SC_RUN_STATE_CHANGE() { }

        private byte[] _entityid;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"entityid", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public byte[] entityid
        {
            get { return _entityid; }
            set { _entityid = value; }
        }
        private bool _isrunning;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"isrunning", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public bool isrunning
        {
            get { return _isrunning; }
            set { _isrunning = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"SC_ROTATE_CHANGE")]
    public partial class SC_ROTATE_CHANGE : global::ProtoBuf.IExtensible
    {
        public SC_ROTATE_CHANGE() { }

        private byte[] _entityid;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"entityid", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public byte[] entityid
        {
            get { return _entityid; }
            set { _entityid = value; }
        }
        private float _rotationY;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"rotationY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float rotationY
        {
            get { return _rotationY; }
            set { _rotationY = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::ProtoBuf.ProtoContract(Name = @"MESSAGE_OPCODE")]
    public enum MESSAGE_OPCODE
    {

        [global::ProtoBuf.ProtoEnum(Name = @"CLIENT_MESSAGE_LUA_MESSAGE", Value = 2)]
        CLIENT_MESSAGE_LUA_MESSAGE = 2,

        [global::ProtoBuf.ProtoEnum(Name = @"SERVER_MESSAGE_OPCODE_LUA_MESSAGE", Value = 3)]
        SERVER_MESSAGE_OPCODE_LUA_MESSAGE = 3,

        [global::ProtoBuf.ProtoEnum(Name = @"CLIENT_MESSAGE_OPCODE_MOVE", Value = 4)]
        CLIENT_MESSAGE_OPCODE_MOVE = 4,

        [global::ProtoBuf.ProtoEnum(Name = @"SERVER_MESSAGE_OPCODE_MOVE", Value = 5)]
        SERVER_MESSAGE_OPCODE_MOVE = 5,

        [global::ProtoBuf.ProtoEnum(Name = @"CLIENT_MESSAGE_OPCODE_STOP_MOVE", Value = 6)]
        CLIENT_MESSAGE_OPCODE_STOP_MOVE = 6,

        [global::ProtoBuf.ProtoEnum(Name = @"SERVER_MESSAGE_OPCODE_STOP_MOVE", Value = 7)]
        SERVER_MESSAGE_OPCODE_STOP_MOVE = 7,

        [global::ProtoBuf.ProtoEnum(Name = @"CLIENT_MESSAGE_FORCE_POSITION", Value = 8)]
        CLIENT_MESSAGE_FORCE_POSITION = 8,

        [global::ProtoBuf.ProtoEnum(Name = @"SERVER_MESSAGE_FORCE_POSITION", Value = 9)]
        SERVER_MESSAGE_FORCE_POSITION = 9,

        [global::ProtoBuf.ProtoEnum(Name = @"CLIENT_MESSAGE_OPCODE_TURN_DIRECTION", Value = 10)]
        CLIENT_MESSAGE_OPCODE_TURN_DIRECTION = 10,

        [global::ProtoBuf.ProtoEnum(Name = @"SERVER_MESSAGE_OPCODE_TURN_DIRECTION", Value = 11)]
        SERVER_MESSAGE_OPCODE_TURN_DIRECTION = 11,

        [global::ProtoBuf.ProtoEnum(Name = @"SERVER_MESSAGE_OPCODE_CREATE_ENTITY", Value = 12)]
        SERVER_MESSAGE_OPCODE_CREATE_ENTITY = 12,

        [global::ProtoBuf.ProtoEnum(Name = @"SERVER_MESSAGE_OPCODE_DESTROY_ENTITY", Value = 13)]
        SERVER_MESSAGE_OPCODE_DESTROY_ENTITY = 13,

        [global::ProtoBuf.ProtoEnum(Name = @"CLIENT_MESSAGE_OPCODE_CONNECT_REQUEST", Value = 20)]
        CLIENT_MESSAGE_OPCODE_CONNECT_REQUEST = 20,

        [global::ProtoBuf.ProtoEnum(Name = @"SERVER_MESSAGE_OPCODE_CONNECT_REPLY", Value = 21)]
        SERVER_MESSAGE_OPCODE_CONNECT_REPLY = 21,

        [global::ProtoBuf.ProtoEnum(Name = @"CLIENT_MESSAGE_OPCODE_PING", Value = 100)]
        CLIENT_MESSAGE_OPCODE_PING = 100,

        [global::ProtoBuf.ProtoEnum(Name = @"SERVER_MESSAGE_OPCODE_PING_BACK", Value = 101)]
        SERVER_MESSAGE_OPCODE_PING_BACK = 101,

        [global::ProtoBuf.ProtoEnum(Name = @"CLIENT_MESSAGE_OPCODE_PING_BACK", Value = 102)]
        CLIENT_MESSAGE_OPCODE_PING_BACK = 102,

        [global::ProtoBuf.ProtoEnum(Name = @"GS_MESSAFE_OPCODE_REGISTER", Value = 10001)]
        GS_MESSAFE_OPCODE_REGISTER = 10001
    }

}