//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RankMessage.proto
namespace RankMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Rank_GetRankList")]
  public partial class CS_Rank_GetRankList : global::ProtoBuf.IExtensible
  {
    public CS_Rank_GetRankList() {}
    
    private uint _RankType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RankType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RankType
    {
      get { return _RankType; }
      set { _RankType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Rank_GetRankList")]
  public partial class SC_Rank_GetRankList : global::ProtoBuf.IExtensible
  {
    public SC_Rank_GetRankList() {}
    
    private uint _RankType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RankType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RankType
    {
      get { return _RankType; }
      set { _RankType = value; }
    }
    private uint _SelfRank;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SelfRank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SelfRank
    {
      get { return _SelfRank; }
      set { _SelfRank = value; }
    }
    private readonly global::System.Collections.Generic.List<SC_Rank_GetRankList.RankData> _RankList = new global::System.Collections.Generic.List<SC_Rank_GetRankList.RankData>();
    [global::ProtoBuf.ProtoMember(3, Name=@"RankList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SC_Rank_GetRankList.RankData> RankList
    {
      get { return _RankList; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankData")]
  public partial class RankData : global::ProtoBuf.IExtensible
  {
    public RankData() {}
    
    private uint _ActorID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ActorID
    {
      get { return _ActorID; }
      set { _ActorID = value; }
    }
    private string _ActorName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActorName
    {
      get { return _ActorName; }
      set { _ActorName = value; }
    }
    private uint _Level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private uint _Vocation;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Vocation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Vocation
    {
      get { return _Vocation; }
      set { _Vocation = value; }
    }
    private int _Value1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Value1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Value1
    {
      get { return _Value1; }
      set { _Value1 = value; }
    }
    private int _Value2;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Value2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Value2
    {
      get { return _Value2; }
      set { _Value2 = value; }
    }
    private uint _VipLevel;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"VipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint VipLevel
    {
      get { return _VipLevel; }
      set { _VipLevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MSG_RANK_ACTIONID")]
    public enum MSG_RANK_ACTIONID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_RANK_NONE", Value=0)]
      MSG_RANK_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_RANK_GETLIST", Value=1)]
      MSG_RANK_GETLIST = 1
    }
  
}