//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SkepMessage.proto
namespace SkepMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Skep_CreateSkep")]
  public partial class SC_Skep_CreateSkep : global::ProtoBuf.IExtensible
  {
    public SC_Skep_CreateSkep() {}
    
    private ulong _SkepUID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SkepUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong SkepUID
    {
      get { return _SkepUID; }
      set { _SkepUID = value; }
    }
    private ulong _MasterUID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"MasterUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong MasterUID
    {
      get { return _MasterUID; }
      set { _MasterUID = value; }
    }
    private uint _Access;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Access", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Access
    {
      get { return _Access; }
      set { _Access = value; }
    }
    private uint _SkepID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"SkepID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SkepID
    {
      get { return _SkepID; }
      set { _SkepID = value; }
    }
    private uint _MaxSize;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"MaxSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MaxSize
    {
      get { return _MaxSize; }
      set { _MaxSize = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Skep_DestorySkep")]
  public partial class SC_Skep_DestorySkep : global::ProtoBuf.IExtensible
  {
    public SC_Skep_DestorySkep() {}
    
    private ulong _SkepUID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SkepUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong SkepUID
    {
      get { return _SkepUID; }
      set { _SkepUID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Skep_SyncPlace")]
  public partial class SC_Skep_SyncPlace : global::ProtoBuf.IExtensible
  {
    public SC_Skep_SyncPlace() {}
    
    private ulong _SkepUID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SkepUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong SkepUID
    {
      get { return _SkepUID; }
      set { _SkepUID = value; }
    }
    private readonly global::System.Collections.Generic.List<SC_Skep_SyncPlace.SkepData> _PlaceList = new global::System.Collections.Generic.List<SC_Skep_SyncPlace.SkepData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"PlaceList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SC_Skep_SyncPlace.SkepData> PlaceList
    {
      get { return _PlaceList; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SkepData")]
  public partial class SkepData : global::ProtoBuf.IExtensible
  {
    public SkepData() {}
    
    private uint _Place;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Place", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Place
    {
      get { return _Place; }
      set { _Place = value; }
    }
    private ulong _GoodsUID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"GoodsUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong GoodsUID
    {
      get { return _GoodsUID; }
      set { _GoodsUID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Skep_SyncSize")]
  public partial class SC_Skep_SyncSize : global::ProtoBuf.IExtensible
  {
    public SC_Skep_SyncSize() {}
    
    private ulong _SkepUID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SkepUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong SkepUID
    {
      get { return _SkepUID; }
      set { _SkepUID = value; }
    }
    private uint _MaxSize;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"MaxSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MaxSize
    {
      get { return _MaxSize; }
      set { _MaxSize = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Skep_UseGoods")]
  public partial class CS_Skep_UseGoods : global::ProtoBuf.IExtensible
  {
    public CS_Skep_UseGoods() {}
    
    private ulong _SkepUID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SkepUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong SkepUID
    {
      get { return _SkepUID; }
      set { _SkepUID = value; }
    }
    private ulong _GoodsUID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"GoodsUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong GoodsUID
    {
      get { return _GoodsUID; }
      set { _GoodsUID = value; }
    }
    private uint _UseNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"UseNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint UseNum
    {
      get { return _UseNum; }
      set { _UseNum = value; }
    }
    private ulong _Target = (ulong)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Target", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((ulong)0)]
    public ulong Target
    {
      get { return _Target; }
      set { _Target = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Skep_UseGoods")]
  public partial class SC_Skep_UseGoods : global::ProtoBuf.IExtensible
  {
    public SC_Skep_UseGoods() {}
    
    private uint _Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Skep_SellGoods")]
  public partial class CS_Skep_SellGoods : global::ProtoBuf.IExtensible
  {
    public CS_Skep_SellGoods() {}
    
    private ulong _SkepUID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SkepUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong SkepUID
    {
      get { return _SkepUID; }
      set { _SkepUID = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _GoodsUID = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(2, Name=@"GoodsUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> GoodsUID
    {
      get { return _GoodsUID; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Skep_SellGoods")]
  public partial class SC_Skep_SellGoods : global::ProtoBuf.IExtensible
  {
    public SC_Skep_SellGoods() {}
    
    private ulong _SkepUID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SkepUID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong SkepUID
    {
      get { return _SkepUID; }
      set { _SkepUID = value; }
    }
    private uint _Result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MSG_SKEP_ACTIONID")]
    public enum MSG_SKEP_ACTIONID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SKEP_NONE", Value=0)]
      MSG_SKEP_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SKEP_CREATE", Value=1)]
      MSG_SKEP_CREATE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SKEP_DESTORY", Value=2)]
      MSG_SKEP_DESTORY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SKEP_SYNCPLACE", Value=3)]
      MSG_SKEP_SYNCPLACE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SKEP_SYNCSIZE", Value=4)]
      MSG_SKEP_SYNCSIZE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SKEP_USEGOODS", Value=5)]
      MSG_SKEP_USEGOODS = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SKEP_SELLGOODS", Value=6)]
      MSG_SKEP_SELLGOODS = 6
    }
  
}