//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SocietyMessage.proto
namespace SocietyMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Society_Create")]
  public partial class CS_Society_Create : global::ProtoBuf.IExtensible
  {
    public CS_Society_Create() {}
    
    private string _SocietyName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SocietyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SocietyName
    {
      get { return _SocietyName; }
      set { _SocietyName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Society_Create")]
  public partial class SC_Society_Create : global::ProtoBuf.IExtensible
  {
    public SC_Society_Create() {}
    
    private uint _SocietyID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyID
    {
      get { return _SocietyID; }
      set { _SocietyID = value; }
    }
    private string _SocietyName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SocietyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SocietyName
    {
      get { return _SocietyName; }
      set { _SocietyName = value; }
    }
    private uint _ChiefID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ChiefID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ChiefID
    {
      get { return _ChiefID; }
      set { _ChiefID = value; }
    }
    private uint _SocietyLevel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"SocietyLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyLevel
    {
      get { return _SocietyLevel; }
      set { _SocietyLevel = value; }
    }
    private uint _SocietyExp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"SocietyExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyExp
    {
      get { return _SocietyExp; }
      set { _SocietyExp = value; }
    }
    private uint _Vitality;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Vitality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Vitality
    {
      get { return _Vitality; }
      set { _Vitality = value; }
    }
    private uint _MemberNum;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"MemberNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MemberNum
    {
      get { return _MemberNum; }
      set { _MemberNum = value; }
    }
    private uint _FeastLeave;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"FeastLeave", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FeastLeave
    {
      get { return _FeastLeave; }
      set { _FeastLeave = value; }
    }
    private uint _FeastAdd;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"FeastAdd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FeastAdd
    {
      get { return _FeastAdd; }
      set { _FeastAdd = value; }
    }
    private uint _LastFeast;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"LastFeast", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LastFeast
    {
      get { return _LastFeast; }
      set { _LastFeast = value; }
    }
    private uint _ChiefLogoutTime;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"ChiefLogoutTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ChiefLogoutTime
    {
      get { return _ChiefLogoutTime; }
      set { _ChiefLogoutTime = value; }
    }
    private string _SocietyInfo;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"SocietyInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SocietyInfo
    {
      get { return _SocietyInfo; }
      set { _SocietyInfo = value; }
    }
    private uint _LevelLimit;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"LevelLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LevelLimit
    {
      get { return _LevelLimit; }
      set { _LevelLimit = value; }
    }
    private uint _JoinLimit;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"JoinLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint JoinLimit
    {
      get { return _JoinLimit; }
      set { _JoinLimit = value; }
    }
    private uint _FeastActor;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"FeastActor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FeastActor
    {
      get { return _FeastActor; }
      set { _FeastActor = value; }
    }
    private string _FeastActorName;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"FeastActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string FeastActorName
    {
      get { return _FeastActorName; }
      set { _FeastActorName = value; }
    }
    private uint _Result;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private uint _BuyRevive;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"BuyRevive", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint BuyRevive
    {
      get { return _BuyRevive; }
      set { _BuyRevive = value; }
    }
    private uint _Revive;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"Revive", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Revive
    {
      get { return _Revive; }
      set { _Revive = value; }
    }
    private uint _PracticeCount;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"PracticeCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PracticeCount
    {
      get { return _PracticeCount; }
      set { _PracticeCount = value; }
    }
    private uint _PracticeTime;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"PracticeTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PracticeTime
    {
      get { return _PracticeTime; }
      set { _PracticeTime = value; }
    }
    private uint _Country;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"Country", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Country
    {
      get { return _Country; }
      set { _Country = value; }
    }
    private uint _PracticeNotice;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"PracticeNotice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PracticeNotice
    {
      get { return _PracticeNotice; }
      set { _PracticeNotice = value; }
    }
    private uint _FeastNotice;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"FeastNotice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FeastNotice
    {
      get { return _FeastNotice; }
      set { _FeastNotice = value; }
    }
    private uint _ContributionNotice;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"ContributionNotice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ContributionNotice
    {
      get { return _ContributionNotice; }
      set { _ContributionNotice = value; }
    }
    private uint _PrizeLimit;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"PrizeLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PrizeLimit
    {
      get { return _PrizeLimit; }
      set { _PrizeLimit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Society_Delete")]
  public partial class CS_Society_Delete : global::ProtoBuf.IExtensible
  {
    public CS_Society_Delete() {}
    
    private uint _SocietyID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyID
    {
      get { return _SocietyID; }
      set { _SocietyID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Society_Delete")]
  public partial class SC_Society_Delete : global::ProtoBuf.IExtensible
  {
    public SC_Society_Delete() {}
    
    private uint _SocietyID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyID
    {
      get { return _SocietyID; }
      set { _SocietyID = value; }
    }
    private uint _Result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private string _SocietyName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"SocietyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SocietyName
    {
      get { return _SocietyName; }
      set { _SocietyName = value; }
    }
    private uint _Initiative;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Initiative", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Initiative
    {
      get { return _Initiative; }
      set { _Initiative = value; }
    }
    private uint _ChiefID;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"ChiefID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ChiefID
    {
      get { return _ChiefID; }
      set { _ChiefID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Society_MemberList")]
  public partial class CS_Society_MemberList : global::ProtoBuf.IExtensible
  {
    public CS_Society_MemberList() {}
    
    private uint _SocietyID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyID
    {
      get { return _SocietyID; }
      set { _SocietyID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Society_MemberList")]
  public partial class SC_Society_MemberList : global::ProtoBuf.IExtensible
  {
    public SC_Society_MemberList() {}
    
    private uint _SocietyID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyID
    {
      get { return _SocietyID; }
      set { _SocietyID = value; }
    }
    private readonly global::System.Collections.Generic.List<SC_Society_MemberList.SocietyMember> _MemberList = new global::System.Collections.Generic.List<SC_Society_MemberList.SocietyMember>();
    [global::ProtoBuf.ProtoMember(2, Name=@"MemberList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SC_Society_MemberList.SocietyMember> MemberList
    {
      get { return _MemberList; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SocietyMember")]
  public partial class SocietyMember : global::ProtoBuf.IExtensible
  {
    public SocietyMember() {}
    
    private uint _ActorID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ActorID
    {
      get { return _ActorID; }
      set { _ActorID = value; }
    }
    private string _ActorName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActorName
    {
      get { return _ActorName; }
      set { _ActorName = value; }
    }
    private uint _Level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private uint _Vocation;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Vocation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Vocation
    {
      get { return _Vocation; }
      set { _Vocation = value; }
    }
    private uint _Power;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Power
    {
      get { return _Power; }
      set { _Power = value; }
    }
    private uint _IsOnline;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"IsOnline", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint IsOnline
    {
      get { return _IsOnline; }
      set { _IsOnline = value; }
    }
    private uint _Title;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"Title", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Title
    {
      get { return _Title; }
      set { _Title = value; }
    }
    private uint _Contribution;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"Contribution", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Contribution
    {
      get { return _Contribution; }
      set { _Contribution = value; }
    }
    private uint _LogoutTime;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"LogoutTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LogoutTime
    {
      get { return _LogoutTime; }
      set { _LogoutTime = value; }
    }
    private uint _SocietyID;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"SocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyID
    {
      get { return _SocietyID; }
      set { _SocietyID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Society_Join")]
  public partial class CS_Society_Join : global::ProtoBuf.IExtensible
  {
    public CS_Society_Join() {}
    
    private uint _SocietyID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyID
    {
      get { return _SocietyID; }
      set { _SocietyID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Society_Join")]
  public partial class SC_Society_Join : global::ProtoBuf.IExtensible
  {
    public SC_Society_Join() {}
    
    private uint _SocietyID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyID
    {
      get { return _SocietyID; }
      set { _SocietyID = value; }
    }
    private string _SocietyName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SocietyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SocietyName
    {
      get { return _SocietyName; }
      set { _SocietyName = value; }
    }
    private uint _ChiefID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ChiefID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ChiefID
    {
      get { return _ChiefID; }
      set { _ChiefID = value; }
    }
    private uint _SocietyLevel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"SocietyLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyLevel
    {
      get { return _SocietyLevel; }
      set { _SocietyLevel = value; }
    }
    private uint _SocietyExp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"SocietyExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyExp
    {
      get { return _SocietyExp; }
      set { _SocietyExp = value; }
    }
    private uint _Vitality;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Vitality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Vitality
    {
      get { return _Vitality; }
      set { _Vitality = value; }
    }
    private uint _MemberNum;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"MemberNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MemberNum
    {
      get { return _MemberNum; }
      set { _MemberNum = value; }
    }
    private uint _FeastLeave;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"FeastLeave", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FeastLeave
    {
      get { return _FeastLeave; }
      set { _FeastLeave = value; }
    }
    private uint _FeastAdd;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"FeastAdd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FeastAdd
    {
      get { return _FeastAdd; }
      set { _FeastAdd = value; }
    }
    private uint _LastFeast;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"LastFeast", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LastFeast
    {
      get { return _LastFeast; }
      set { _LastFeast = value; }
    }
    private uint _ChiefLogoutTime;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"ChiefLogoutTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ChiefLogoutTime
    {
      get { return _ChiefLogoutTime; }
      set { _ChiefLogoutTime = value; }
    }
    private string _SocietyInfo;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"SocietyInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SocietyInfo
    {
      get { return _SocietyInfo; }
      set { _SocietyInfo = value; }
    }
    private uint _LevelLimit;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"LevelLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LevelLimit
    {
      get { return _LevelLimit; }
      set { _LevelLimit = value; }
    }
    private uint _JoinLimit;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"JoinLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint JoinLimit
    {
      get { return _JoinLimit; }
      set { _JoinLimit = value; }
    }
    private uint _FeastActor;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"FeastActor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FeastActor
    {
      get { return _FeastActor; }
      set { _FeastActor = value; }
    }
    private string _FeastActorName;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"FeastActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string FeastActorName
    {
      get { return _FeastActorName; }
      set { _FeastActorName = value; }
    }
    private uint _Result;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private uint _BuyRevive;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"BuyRevive", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint BuyRevive
    {
      get { return _BuyRevive; }
      set { _BuyRevive = value; }
    }
    private uint _Revive;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"Revive", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Revive
    {
      get { return _Revive; }
      set { _Revive = value; }
    }
    private uint _PracticeCount;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"PracticeCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PracticeCount
    {
      get { return _PracticeCount; }
      set { _PracticeCount = value; }
    }
    private uint _PracticeTime;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"PracticeTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PracticeTime
    {
      get { return _PracticeTime; }
      set { _PracticeTime = value; }
    }
    private uint _Country;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"Country", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Country
    {
      get { return _Country; }
      set { _Country = value; }
    }
    private uint _PracticeNotice;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"PracticeNotice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PracticeNotice
    {
      get { return _PracticeNotice; }
      set { _PracticeNotice = value; }
    }
    private uint _FeastNotice;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"FeastNotice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FeastNotice
    {
      get { return _FeastNotice; }
      set { _FeastNotice = value; }
    }
    private uint _ContributionNotice;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"ContributionNotice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ContributionNotice
    {
      get { return _ContributionNotice; }
      set { _ContributionNotice = value; }
    }
    private uint _PrizeLimit;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"PrizeLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PrizeLimit
    {
      get { return _PrizeLimit; }
      set { _PrizeLimit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Society_Leave")]
  public partial class CS_Society_Leave : global::ProtoBuf.IExtensible
  {
    public CS_Society_Leave() {}
    
    private uint _SocietyID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyID
    {
      get { return _SocietyID; }
      set { _SocietyID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Society_Leave")]
  public partial class SC_Society_Leave : global::ProtoBuf.IExtensible
  {
    public SC_Society_Leave() {}
    
    private uint _SocietyID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyID
    {
      get { return _SocietyID; }
      set { _SocietyID = value; }
    }
    private uint _Result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private string _SocietyName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"SocietyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SocietyName
    {
      get { return _SocietyName; }
      set { _SocietyName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Society_Kick")]
  public partial class CS_Society_Kick : global::ProtoBuf.IExtensible
  {
    public CS_Society_Kick() {}
    
    private uint _SocietyID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyID
    {
      get { return _SocietyID; }
      set { _SocietyID = value; }
    }
    private uint _KickActorID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"KickActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint KickActorID
    {
      get { return _KickActorID; }
      set { _KickActorID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Society_Kick")]
  public partial class SC_Society_Kick : global::ProtoBuf.IExtensible
  {
    public SC_Society_Kick() {}
    
    private uint _ActorID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ActorID
    {
      get { return _ActorID; }
      set { _ActorID = value; }
    }
    private uint _SocietyID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyID
    {
      get { return _SocietyID; }
      set { _SocietyID = value; }
    }
    private uint _KickActorID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"KickActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint KickActorID
    {
      get { return _KickActorID; }
      set { _KickActorID = value; }
    }
    private uint _Result;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Society_Appoint")]
  public partial class CS_Society_Appoint : global::ProtoBuf.IExtensible
  {
    public CS_Society_Appoint() {}
    
    private uint _SocietyID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyID
    {
      get { return _SocietyID; }
      set { _SocietyID = value; }
    }
    private uint _AppointActorID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"AppointActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AppointActorID
    {
      get { return _AppointActorID; }
      set { _AppointActorID = value; }
    }
    private uint _Title;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Title", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Title
    {
      get { return _Title; }
      set { _Title = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Society_Appoint")]
  public partial class SC_Society_Appoint : global::ProtoBuf.IExtensible
  {
    public SC_Society_Appoint() {}
    
    private uint _ActorID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ActorID
    {
      get { return _ActorID; }
      set { _ActorID = value; }
    }
    private uint _SocietyID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyID
    {
      get { return _SocietyID; }
      set { _SocietyID = value; }
    }
    private uint _AppointActorID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"AppointActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AppointActorID
    {
      get { return _AppointActorID; }
      set { _AppointActorID = value; }
    }
    private uint _Title;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Title", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Title
    {
      get { return _Title; }
      set { _Title = value; }
    }
    private uint _Result;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Society_Succeed")]
  public partial class CS_Society_Succeed : global::ProtoBuf.IExtensible
  {
    public CS_Society_Succeed() {}
    
    private uint _SocietyID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyID
    {
      get { return _SocietyID; }
      set { _SocietyID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Society_Succeed")]
  public partial class SC_Society_Succeed : global::ProtoBuf.IExtensible
  {
    public SC_Society_Succeed() {}
    
    private uint _ActorID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ActorID
    {
      get { return _ActorID; }
      set { _ActorID = value; }
    }
    private uint _SocietyID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyID
    {
      get { return _SocietyID; }
      set { _SocietyID = value; }
    }
    private uint _PreChiefID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"PreChiefID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PreChiefID
    {
      get { return _PreChiefID; }
      set { _PreChiefID = value; }
    }
    private uint _Result;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Society_GetList")]
  public partial class CS_Society_GetList : global::ProtoBuf.IExtensible
  {
    public CS_Society_GetList() {}
    
    private uint _BeginSocietyID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"BeginSocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint BeginSocietyID
    {
      get { return _BeginSocietyID; }
      set { _BeginSocietyID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Society_GetList")]
  public partial class SC_Society_GetList : global::ProtoBuf.IExtensible
  {
    public SC_Society_GetList() {}
    
    private readonly global::System.Collections.Generic.List<SC_Society_GetList.SocietyData> _SocietyList = new global::System.Collections.Generic.List<SC_Society_GetList.SocietyData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"SocietyList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SC_Society_GetList.SocietyData> SocietyList
    {
      get { return _SocietyList; }
    }
  
    private uint _BeginSocietyID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"BeginSocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint BeginSocietyID
    {
      get { return _BeginSocietyID; }
      set { _BeginSocietyID = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SocietyData")]
  public partial class SocietyData : global::ProtoBuf.IExtensible
  {
    public SocietyData() {}
    
    private uint _SocietyID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyID
    {
      get { return _SocietyID; }
      set { _SocietyID = value; }
    }
    private string _SocietyName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SocietyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SocietyName
    {
      get { return _SocietyName; }
      set { _SocietyName = value; }
    }
    private uint _MemberNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"MemberNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MemberNum
    {
      get { return _MemberNum; }
      set { _MemberNum = value; }
    }
    private string _SocietyInfo;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"SocietyInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SocietyInfo
    {
      get { return _SocietyInfo; }
      set { _SocietyInfo = value; }
    }
    private uint _LevelLimit;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"LevelLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LevelLimit
    {
      get { return _LevelLimit; }
      set { _LevelLimit = value; }
    }
    private uint _JoinLimit;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"JoinLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint JoinLimit
    {
      get { return _JoinLimit; }
      set { _JoinLimit = value; }
    }
    private uint _Country;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"Country", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Country
    {
      get { return _Country; }
      set { _Country = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Society_Find")]
  public partial class CS_Society_Find : global::ProtoBuf.IExtensible
  {
    public CS_Society_Find() {}
    
    private string _SocietyName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SocietyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SocietyName
    {
      get { return _SocietyName; }
      set { _SocietyName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Society_Find")]
  public partial class SC_Society_Find : global::ProtoBuf.IExtensible
  {
    public SC_Society_Find() {}
    
    private uint _SocietyID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyID
    {
      get { return _SocietyID; }
      set { _SocietyID = value; }
    }
    private string _SocietyName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SocietyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SocietyName
    {
      get { return _SocietyName; }
      set { _SocietyName = value; }
    }
    private uint _MemberNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"MemberNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MemberNum
    {
      get { return _MemberNum; }
      set { _MemberNum = value; }
    }
    private string _SocietyInfo;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"SocietyInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SocietyInfo
    {
      get { return _SocietyInfo; }
      set { _SocietyInfo = value; }
    }
    private uint _LevelLimit;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"LevelLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LevelLimit
    {
      get { return _LevelLimit; }
      set { _LevelLimit = value; }
    }
    private uint _JoinLimit;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"JoinLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint JoinLimit
    {
      get { return _JoinLimit; }
      set { _JoinLimit = value; }
    }
    private uint _Result;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private uint _Country;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"Country", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Country
    {
      get { return _Country; }
      set { _Country = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Society_Info")]
  public partial class CS_Society_Info : global::ProtoBuf.IExtensible
  {
    public CS_Society_Info() {}
    
    private uint _SocietyID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyID
    {
      get { return _SocietyID; }
      set { _SocietyID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Society_Info")]
  public partial class SC_Society_Info : global::ProtoBuf.IExtensible
  {
    public SC_Society_Info() {}
    
    private uint _SocietyID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyID
    {
      get { return _SocietyID; }
      set { _SocietyID = value; }
    }
    private string _SocietyName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SocietyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SocietyName
    {
      get { return _SocietyName; }
      set { _SocietyName = value; }
    }
    private uint _ChiefID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ChiefID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ChiefID
    {
      get { return _ChiefID; }
      set { _ChiefID = value; }
    }
    private uint _SocietyLevel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"SocietyLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyLevel
    {
      get { return _SocietyLevel; }
      set { _SocietyLevel = value; }
    }
    private uint _SocietyExp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"SocietyExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyExp
    {
      get { return _SocietyExp; }
      set { _SocietyExp = value; }
    }
    private uint _Vitality;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Vitality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Vitality
    {
      get { return _Vitality; }
      set { _Vitality = value; }
    }
    private uint _MemberNum;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"MemberNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MemberNum
    {
      get { return _MemberNum; }
      set { _MemberNum = value; }
    }
    private uint _FeastLeave;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"FeastLeave", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FeastLeave
    {
      get { return _FeastLeave; }
      set { _FeastLeave = value; }
    }
    private uint _FeastAdd;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"FeastAdd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FeastAdd
    {
      get { return _FeastAdd; }
      set { _FeastAdd = value; }
    }
    private uint _LastFeast;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"LastFeast", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LastFeast
    {
      get { return _LastFeast; }
      set { _LastFeast = value; }
    }
    private uint _ChiefLogoutTime;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"ChiefLogoutTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ChiefLogoutTime
    {
      get { return _ChiefLogoutTime; }
      set { _ChiefLogoutTime = value; }
    }
    private string _SocietyInfo;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"SocietyInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SocietyInfo
    {
      get { return _SocietyInfo; }
      set { _SocietyInfo = value; }
    }
    private uint _LevelLimit;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"LevelLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LevelLimit
    {
      get { return _LevelLimit; }
      set { _LevelLimit = value; }
    }
    private uint _JoinLimit;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"JoinLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint JoinLimit
    {
      get { return _JoinLimit; }
      set { _JoinLimit = value; }
    }
    private uint _FeastActor;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"FeastActor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FeastActor
    {
      get { return _FeastActor; }
      set { _FeastActor = value; }
    }
    private string _FeastActorName;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"FeastActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string FeastActorName
    {
      get { return _FeastActorName; }
      set { _FeastActorName = value; }
    }
    private uint _Result;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private uint _BuyRevive;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"BuyRevive", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint BuyRevive
    {
      get { return _BuyRevive; }
      set { _BuyRevive = value; }
    }
    private uint _Revive;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"Revive", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Revive
    {
      get { return _Revive; }
      set { _Revive = value; }
    }
    private uint _PracticeCount;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"PracticeCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PracticeCount
    {
      get { return _PracticeCount; }
      set { _PracticeCount = value; }
    }
    private uint _PracticeTime;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"PracticeTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PracticeTime
    {
      get { return _PracticeTime; }
      set { _PracticeTime = value; }
    }
    private uint _Country;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"Country", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Country
    {
      get { return _Country; }
      set { _Country = value; }
    }
    private uint _PracticeNotice;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"PracticeNotice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PracticeNotice
    {
      get { return _PracticeNotice; }
      set { _PracticeNotice = value; }
    }
    private uint _FeastNotice;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"FeastNotice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FeastNotice
    {
      get { return _FeastNotice; }
      set { _FeastNotice = value; }
    }
    private uint _ContributionNotice;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"ContributionNotice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ContributionNotice
    {
      get { return _ContributionNotice; }
      set { _ContributionNotice = value; }
    }
    private uint _PrizeLimit;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"PrizeLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PrizeLimit
    {
      get { return _PrizeLimit; }
      set { _PrizeLimit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Society_ApplyList")]
  public partial class CS_Society_ApplyList : global::ProtoBuf.IExtensible
  {
    public CS_Society_ApplyList() {}
    
    private uint _SocietyID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SocietyID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SocietyID
    {
      get { return _SocietyID; }
      set { _SocietyID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Society_ApplyList")]
  public partial class SC_Society_ApplyList : global::ProtoBuf.IExtensible
  {
    public SC_Society_ApplyList() {}
    
    private readonly global::System.Collections.Generic.List<SC_Society_ApplyList.ApplyData> _ApplyList = new global::System.Collections.Generic.List<SC_Society_ApplyList.ApplyData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ApplyList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SC_Society_ApplyList.ApplyData> ApplyList
    {
      get { return _ApplyList; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ApplyData")]
  public partial class ApplyData : global::ProtoBuf.IExtensible
  {
    public ApplyData() {}
    
    private uint _PrizeID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PrizeID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PrizeID
    {
      get { return _PrizeID; }
      set { _PrizeID = value; }
    }
    private uint _PrizeNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"PrizeNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PrizeNum
    {
      get { return _PrizeNum; }
      set { _PrizeNum = value; }
    }
    private uint _LastTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"LastTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LastTime
    {
      get { return _LastTime; }
      set { _LastTime = value; }
    }
    private readonly global::System.Collections.Generic.List<SC_Society_ApplyList.ApplyData.Applicant> _ApplicantList = new global::System.Collections.Generic.List<SC_Society_ApplyList.ApplyData.Applicant>();
    [global::ProtoBuf.ProtoMember(4, Name=@"ApplicantList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SC_Society_ApplyList.ApplyData.Applicant> ApplicantList
    {
      get { return _ApplicantList; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Applicant")]
  public partial class Applicant : global::ProtoBuf.IExtensible
  {
    public Applicant() {}
    
    private uint _ActorID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ActorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ActorID
    {
      get { return _ActorID; }
      set { _ActorID = value; }
    }
    private string _ActorName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ActorName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ActorName
    {
      get { return _ActorName; }
      set { _ActorName = value; }
    }
    private uint _Power;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Power
    {
      get { return _Power; }
      set { _Power = value; }
    }
    private uint _Level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MSG_SOCIETY_ACTIONID")]
    public enum MSG_SOCIETY_ACTIONID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SOCIETY_NONE", Value=0)]
      MSG_SOCIETY_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SOCIETY_CREATE", Value=1)]
      MSG_SOCIETY_CREATE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SOCIETY_DELETE", Value=2)]
      MSG_SOCIETY_DELETE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SOCIETY_MEMBERLIST", Value=3)]
      MSG_SOCIETY_MEMBERLIST = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SOCIETY_JOIN", Value=4)]
      MSG_SOCIETY_JOIN = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SOCIETY_LEAVE", Value=5)]
      MSG_SOCIETY_LEAVE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SOCIETY_KICK", Value=6)]
      MSG_SOCIETY_KICK = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SOCIETY_APPOINT", Value=7)]
      MSG_SOCIETY_APPOINT = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SOCIETY_SUCCEED", Value=8)]
      MSG_SOCIETY_SUCCEED = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SOCIETY_GETLIST", Value=9)]
      MSG_SOCIETY_GETLIST = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SOCIETY_FIND", Value=10)]
      MSG_SOCIETY_FIND = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SOCIETY_INFO", Value=11)]
      MSG_SOCIETY_INFO = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_SOCIETY_APPLYLIST", Value=12)]
      MSG_SOCIETY_APPLYLIST = 12
    }
  
}