//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: StoreMessage.proto
namespace StoreMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Store_GetItemList")]
  public partial class CS_Store_GetItemList : global::ProtoBuf.IExtensible
  {
    public CS_Store_GetItemList() {}
    
    private uint _StoreID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"StoreID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint StoreID
    {
      get { return _StoreID; }
      set { _StoreID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Store_GetItemList")]
  public partial class SC_Store_GetItemList : global::ProtoBuf.IExtensible
  {
    public SC_Store_GetItemList() {}
    
    private uint _StoreID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"StoreID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint StoreID
    {
      get { return _StoreID; }
      set { _StoreID = value; }
    }
    private readonly global::System.Collections.Generic.List<SC_Store_GetItemList.ItemData> _ItemList = new global::System.Collections.Generic.List<SC_Store_GetItemList.ItemData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"ItemList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SC_Store_GetItemList.ItemData> ItemList
    {
      get { return _ItemList; }
    }
  
    private uint _RefreshID = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"RefreshID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint RefreshID
    {
      get { return _RefreshID; }
      set { _RefreshID = value; }
    }
    private uint _RefreshTime = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"RefreshTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint RefreshTime
    {
      get { return _RefreshTime; }
      set { _RefreshTime = value; }
    }
    private uint _RefreshNum = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"RefreshNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint RefreshNum
    {
      get { return _RefreshNum; }
      set { _RefreshNum = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemData")]
  public partial class ItemData : global::ProtoBuf.IExtensible
  {
    public ItemData() {}
    
    private uint _ItemID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ItemID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ItemID
    {
      get { return _ItemID; }
      set { _ItemID = value; }
    }
    private uint _GoodsID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"GoodsID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint GoodsID
    {
      get { return _GoodsID; }
      set { _GoodsID = value; }
    }
    private uint _GoodsNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"GoodsNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint GoodsNum
    {
      get { return _GoodsNum; }
      set { _GoodsNum = value; }
    }
    private uint _CostType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"CostType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint CostType
    {
      get { return _CostType; }
      set { _CostType = value; }
    }
    private uint _CostNum;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"CostNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint CostNum
    {
      get { return _CostNum; }
      set { _CostNum = value; }
    }
    private bool _SoldOut;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"SoldOut", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool SoldOut
    {
      get { return _SoldOut; }
      set { _SoldOut = value; }
    }
    private uint _Discount;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"Discount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Discount
    {
      get { return _Discount; }
      set { _Discount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Store_BuyItem")]
  public partial class CS_Store_BuyItem : global::ProtoBuf.IExtensible
  {
    public CS_Store_BuyItem() {}
    
    private uint _StoreID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"StoreID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint StoreID
    {
      get { return _StoreID; }
      set { _StoreID = value; }
    }
    private uint _ItemID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ItemID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ItemID
    {
      get { return _ItemID; }
      set { _ItemID = value; }
    }
    private uint _ItemNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ItemNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ItemNum
    {
      get { return _ItemNum; }
      set { _ItemNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Store_BuyItem")]
  public partial class SC_Store_BuyItem : global::ProtoBuf.IExtensible
  {
    public SC_Store_BuyItem() {}
    
    private uint _Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private uint _StoreID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"StoreID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint StoreID
    {
      get { return _StoreID; }
      set { _StoreID = value; }
    }
    private uint _ItemID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ItemID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ItemID
    {
      get { return _ItemID; }
      set { _ItemID = value; }
    }
    private bool _SoldOut;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"SoldOut", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool SoldOut
    {
      get { return _SoldOut; }
      set { _SoldOut = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Store_Refresh")]
  public partial class CS_Store_Refresh : global::ProtoBuf.IExtensible
  {
    public CS_Store_Refresh() {}
    
    private uint _StoreID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"StoreID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint StoreID
    {
      get { return _StoreID; }
      set { _StoreID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Store_Refresh")]
  public partial class SC_Store_Refresh : global::ProtoBuf.IExtensible
  {
    public SC_Store_Refresh() {}
    
    private uint _Result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MSG_STORE_ACTIONID")]
    public enum MSG_STORE_ACTIONID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_STORE_NONE", Value=0)]
      MSG_STORE_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_STORE_GETLIST", Value=1)]
      MSG_STORE_GETLIST = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_STORE_BUYITEM", Value=2)]
      MSG_STORE_BUYITEM = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MSG_STORE_REFRESH", Value=3)]
      MSG_STORE_REFRESH = 3
    }
  
}